export const MOVIES_LOADING = "MOVIES_LOADING";
export const MOVIES_ERROR = "MOVIES_ERROR";
export const MOVIES_SUCESS = "MOVIES_SUCESS";
export const ADD_TO_SHORTLIST = "ADD_TO_SHORTLIST";
export const REMOVE_FROM_SHORTLIST = "REMOVE_FROM_SHORTLIST";
