export const MOVIES_LOADING = "MOVIES_LOADING";
export const MOVIES_ERROR = "MOVIES_ERROR";
export const MOVIES_SUCESS = "MOVIES_SUCESS";
export const ADD_REMOVE_SHORTLIST = "ADD_REMOVE_SHORTLIST";
export const REMOVE_FROM_SHORTLIST = "REMOVE_FROM_SHORTLIST";
